const http=require('http'),fs=require('fs'),path=require('path'),url=require('url');
const root=__dirname;
function loadEnv(){const f=path.join(root,'.env.local');if(!fs.existsSync(f))return;for(const line of fs.readFileSync(f,'utf8').split(/\r?\n/)){const i=line.indexOf('=');if(i>0&&!line.trim().startsWith('#'))process.env[line.slice(0,i).trim()]=line.slice(i+1).trim()}}
loadEnv();
function mockPlan(body){const r=body.region||'성수',start=body.start||'14:00';const add=(t,m)=>{let [h,n]=t.split(':').map(Number),x=h*60+n+m;return `${String(Math.floor(x/60)%24).padStart(2,'0')}:${String(x%60).padStart(2,'0')}`};const make=(style,names)=>{let t=start,total=0;const stops=names.map((x,i)=>{const duration=[65,70,55,75,40][i]||55,start=t,end=add(t,duration),cost=[34000,28000,16000,42000,0][i]||0;t=end;total+=cost;return{id:String(i+1),type:['식사','전시','카페','체험','산책'][i],emoji:['🍽️','🖼️','☕','🎨','🌿'][i],name:x,x:127.05+i*.002,y:37.544+i*.001,address:'서울 성동구',duration,cost,indoor:i!==4,start,end,source:'kakao'}});const moves=[];for(let i=0;i<stops.length-1;i++){const minutes=8+i*2,m={mode:body.transport==='자차'?'🚗 자차':'🚇 대중교통',minutes,cost:body.transport==='자차'?700:3100,distance:1200+i*250,transfers:i%2,steps:[{guidance:i%2?'2호선 탑승 후 2개 역 이동':'도보 4분 후 버스 2016 탑승',minutes}],source:'mock-kakao'};m.from=stops[i].end;m.to=add(m.from,minutes);stops[i+1].start=m.to;stops[i+1].end=add(m.to,stops[i+1].duration);moves.push(m);total+=m.cost}return{id:'mock_'+style,style,region:r,date:body.date,start,end:stops.at(-1).end,stops,moves,totalCost:total,moveMinutes:moves.reduce((s,x)=>s+x.minutes,0),totalDuration:390,score:style==='best'?96:style==='budget'?91:88,title:style==='best'?`${r} 실제 데이터 코스`:style==='budget'?'부담 없이 알차게':'오늘은 평소와 다르게',desc:'실제 API 응답 형태를 기준으로 구성한 테스트 코스예요.',weather:{available:true,sky:'구름많음',temp:27,pop:20,summary:'구름많음'},liveData:true}};return {weather:{available:true,sky:'구름많음',temp:27,pop:20,summary:'구름많음'},courses:[make('best',[`${r} 다이닝`,`서울숲 갤러리`,`로스터리 카페`,`향수 공방`,`서울숲 산책`]),make('budget',[`${r} 가정식`,`무료 전시`,`골목 카페`,`소품샵`,`공원 산책`]),make('special',[`${r} 키친`,`미디어 전시`,`디저트 바`,`도자기 공방`,`야경 산책`])],source:{places:'Kakao Local'}}}
const server=http.createServer(async(req,res)=>{const u=url.parse(req.url,true);if(u.pathname.startsWith('/api/')){if(process.env.MOCK_API==='1'){res.setHeader('Content-Type','application/json; charset=utf-8');if(u.pathname==='/api/plan'){let b='';for await(const c of req)b+=c;return res.end(JSON.stringify(mockPlan(JSON.parse(b||'{}'))))}if(u.pathname==='/api/places')return res.end(JSON.stringify({places:[1,2,3].map(i=>({id:'rp'+i,type:u.query.type||'카페',emoji:'☕',name:`실제 후보 장소 ${i}`,x:127.05+i*.001,y:37.544+i*.001,address:'서울 성동구 테스트로',duration:55,cost:12000+i*2000,indoor:true}))}));if(u.pathname==='/api/route')return res.end(JSON.stringify({mode:u.query.mode==='자차'?'🚗 자차':'🚇 대중교통',minutes:11,cost:3100,distance:1800,transfers:1,steps:[{guidance:'도보 3분 후 2호선 탑승',minutes:3},{guidance:'2개 역 이동 후 하차',minutes:6}],source:'mock'}));return res.end(JSON.stringify({ok:true}))}
    const name=u.pathname.slice(5);try{const handler=require(path.join(root,'api',name+'.js'));let body='';for await(const c of req)body+=c;req.query=u.query;req.body=body?JSON.parse(body):{};const rr={statusCode:200,headers:{},setHeader(k,v){this.headers[k]=v},status(n){this.statusCode=n;return this},json(obj){res.writeHead(this.statusCode,{...this.headers,'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(obj))}};return await handler(req,rr)}catch(e){res.writeHead(500,{'Content-Type':'application/json'});return res.end(JSON.stringify({error:e.message}))}}
 let f=u.pathname==='/'?'index.html':u.pathname.slice(1);f=path.join(root,f);if(!f.startsWith(root)||!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);return res.end('Not found')}const ext=path.extname(f),ct=ext==='.html'?'text/html; charset=utf-8':ext==='.js'?'text/javascript':'application/octet-stream';res.writeHead(200,{'Content-Type':ct});fs.createReadStream(f).pipe(res)});
const port=Number(process.env.PORT)||4173;server.listen(port,()=>console.log(`DATE OS v3 http://127.0.0.1:${port} mock=${process.env.MOCK_API==='1'}`));
